[package]
name = "RCli"
version = "0.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ratatui = "0.26.1"                                      #Fabulous terminal
serde = { version = "1.0", features = ["derive"] }      #serialize, desirialize
serde_json = "1.0"                                      #json reader
regex = "1.10.4"                                        #directory/file matching
once_cell = "1.19.0"                                    #data lock

[dependencies.uuid]                                     #UUID
version = "1.8.0"
features = [
    "v4",                                               # Lets you generate random UUIDs
    "fast-rng",                                         # Use a faster (but still sufficiently random) RNG
    "macro-diagnostics",                                # Enable better diagnostics for compile-time UUIDs
]
